create table if not exists public.summaries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  url text not null,
  title text,
  summary text not null,
  created_at timestamptz not null default now()
);

alter table public.summaries enable row level security;

create policy "Users can read their summaries"
on public.summaries for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their summaries"
on public.summaries for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can delete their summaries"
on public.summaries for delete
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists summaries_user_created_at_idx
on public.summaries (user_id, created_at desc);
